<?php


acf_add_local_field_group(array(
	'key' => 'group_5c9e5f1b6d247',
	'title' => 'Member Documents',
	'fields' => array(
		array(
			'key' => 'field_5c9e6181857a0',
			'label' => 'Documents',
			'name' => 'documents',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => '',
			'button_label' => 'Add Document Category',
			'sub_fields' => array(
				array(
					'key' => 'field_5c9e629380921',
					'label' => 'Category Title',
					'name' => 'category_title',
					'type' => 'text',
					'required' => 1,
				),				
				array(
					'key' => 'field_5c9e61f9ccf95',
					'label' => 'Categories',
					'name' => 'categories',
					'type' => 'repeater',
					'layout' => 'table',
					'button_label' => 'Add Documents',
					'sub_fields' => array(
						array(
							'key' => 'field_5c9e621bb229c',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c9e6225b229d',
							'label' => 'File',
							'name' => 'file',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '4663',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));
